### ISSUE TITLE
Logout seems to be not working

### ISSUE THREAD

**Issue by Frzurita** [mParticle/mparticle-sdk-javascript#8]
Hi! I guess the error is not about logout itself but the way the user is login. My use case is the following:

- Login (known user):
  `mParticle.Identity.login({userIdentities: {customerid: '176985'}})`
- Check user identities:
  `mParticle.Identity.getCurrentUser().getUserIdentities().userIdentities`
  Response: {customerid: "176985"} => Good
- Logout:
  `mParticle.Identity.logout()`
- Check user identities:
  `mParticle.Identity.getCurrentUser().getUserIdentities().userIdentities`
   Response: {} => Good

- Login (New user):
  `mParticle.Identity.login({userIdentities: {customerid: '5555555'}})`
- Check user identities:
  `mParticle.Identity.getCurrentUser().getUserIdentities().userIdentities`
  Response: {customerid: "5555555"} => Good
- Logout:
  `mParticle.Identity.logout()`
- Check user identities:
  `mParticle.Identity.getCurrentUser().getUserIdentities().userIdentities`
   Response: {customerid: "5555555"} => Issue

That's what is happening. Maybe is because some how, the new user is being setted as default user in mParticle.

How can I avoid this use cases?

Thanks

**Comment by samdozor** [comment]
hey @Frzurita can you confirm that your MPID/user id is changing after the 2nd logout? Also just to be sure, since the call is asynchronous - are you always waiting until the logout completes to check the user identities?

**Comment by Frzurita** [comment]
hi @samdozor, the MPID is changing after the second logout. Also, I wait until the logout is finished before check what are the userIdentities values. 

I think it has to be something related with some first login action but I don't know what is happening exactly.

Thanks for the help

**Comment by samdozor** [comment]
hey @Frzurita please reach out to us at support@mparticle.com, or if you're otherwise in direct contact with your mParticle Solution Engineer or Custom Success Manager, they'll get you connected to our technical support team to dig in. Thanks!
